#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homePage:
  path: /
  controller: App\Controller\HomePageController::index
new_blog_post:
  path: /posts/new
  controller: App\Controller\BlogPostsController::newBlogPost
show_blog_post:
  path: /posts/{id}
  controller: App\Controller\BlogPostsController::showBlogPost

registration:
  path: /registration
  controller: App\Controller\RegistrationController::index
login:
  path: /login
  controller: App\Controller\SecurityController::login
logout:
  path: /logout
  controller: App\Controller\LogoutController::index

