#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homePage:
  path: /
  controller: App\Controller\HomePageController::index

new_blog_post:
  path: /posts/new
  controller: App\Controller\BlogPostsController::newBlogPost
show_blog_post:
  path: /posts/{id}
  controller: App\Controller\BlogPostsController::showBlogPost
upvote_blog_post:
  path: /posts/{id}/upvote
  controller: App\Controller\BlogPostsController::upvoteBlogPost
  methods: POST
favorite_blog_post:
  path: /posts/{id}/favorite
  controller: App\Controller\BlogPostsController::favoriteBlogPost
  methods: POST
unfavorite_blog_post:
  path: /posts/{id}/unfavorite
  controller: App\Controller\BlogPostsController::unfavoriteBlogPost
  methods: POST
edit_blog_post:
  path: /posts/{id}/edit
  controller: App\Controller\BlogPostsController::editBlogPost
delete_blog_post:
  path: /posts/{id}/delete
  controller: App\Controller\BlogPostsController::deleteBlogPost

delete_comment:
  path: /comments/{id}/delete
  controller: App\Controller\CommentsController::deleteComment


categories:
  path: /categories/category/{category-id}/edit
  controller: App\Controller\UserController::editCategory

user_profile:
  path: /profile/{userId}
  controller: App\Controller\UserController::index
edit_user_profile:
  path: /profile/edit/{userId}
  controller: App\Controller\UserController::editProfile

registration:
  path: /registration
  controller: App\Controller\RegistrationController::index
login:
  path: /login
  controller: App\Controller\SecurityController::login
logout:
  path: /logout
  controller: App\Controller\LogoutController::index

